In [2]:
import numpy as np

In [1]:
! cat magic.ipynb

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "def Matrix(*a):\n",
    "    if len(a)==1 and isinstance(a[0], np.ndarray):\n",
    "        a = a[0]\n",
    "    return np.array([[float(x) for x in r] for r in a])\n",
    "\n",
    "def Vector(*a):\n",
    "    if len(a)==1 and isinstance(a[0], np.ndarray):\n",
    "        a = a[0]\n",
    "    return np.array([float(x) for x in a]).reshape(-1,1)\n",
    "\n",
    "# Black magic\n",
    "from IPython.display import Latex, SVG, display\n",
    "from IPython.core.interactiveshell import InteractiveShell\n",
    "\n",
    "def ndarray_to_latex(arr): \n",
    "    if len(arr.shape)==1: \n",
    "        arr=arr.reshape(1,-1)\n",
    "    if len(arr.shape) == 2:\n",
    "        if max(arr.shape) > 30:\n",
    "            return None\n",
    "        str_arr = np.vectorize(\"{:.3f}\".format)(arr)\n",

In [4]:
%run magic.ipynb
# or copy paste the cell from https://github.com/tjwei/CrashCourseML/blob/master/DIY_NN/magic.ipynb

## Feedforward Network
一樣有輸入 x, 輸出  y。 但是中間預測、計算的樣子有點不同。
<img src="https://upload.wikimedia.org/wikipedia/en/5/54/Feed_forward_neural_net.gif" />




### 模型是這樣的
一樣考慮輸入是四維向量，輸出有 3 個類別。

我們的輸入 $x=\begin{pmatrix} x_0 \\ x_1 \\ x_2 \\ x_3 \end{pmatrix} $ 是一個向量，我們看成 column vector 好了

### 第 0 層
而 Weight: $ 
W^{(0)} = \begin{pmatrix} W^{(0)}_0 \\ W^{(0)}_1 \\ W^{(0)}_2 \\ W^{(0)}_3 \\ W^{(0)}_4 \\ W^{(0)}_5 \end{pmatrix} =  
\begin{pmatrix} 
W^{(0)}_{0,0} & W^{(0)}_{0,1} &  W^{(0)}_{0,2} & W^{(0)}_{0,3}\\ 
W^{(0)}_{0,0} & W^{(0)}_{0,1} &  W^{(0)}_{0,2} & W^{(0)}_{0,3}\\ 
W^{(0)}_{0,0} & W^{(0)}_{0,1} &  W^{(0)}_{0,2} & W^{(0)}_{0,3}\\ 
W^{(0)}_{0,0} & W^{(0)}_{0,1} &  W^{(0)}_{0,2} & W^{(0)}_{0,3}\\ 
W^{(0)}_{0,0} & W^{(0)}_{0,1} &  W^{(0)}_{0,2} & W^{(0)}_{0,3}\\ 
W^{(0)}_{0,0} & W^{(0)}_{0,1} &  W^{(0)}_{0,2} & W^{(0)}_{0,3}
 \end{pmatrix} $
 
 Bias: $b^{(0)}=\begin{pmatrix} b^{(0)}_0 \\ b^{(0)}_1 \\ b^{(0)}_2  \\ b^{(0)}_3 \\ b^{(0)}_4 \\ b^{(0)}_5 \end{pmatrix} $ 


我們先計算"線性輸出"  $ c^{(0)} = \begin{pmatrix} c^{(0)}_0 \\ c^{(0)}_1 \\ c^{(0)}_2  \\ c^{(0)}_3 \\ c^{(0)}_4 \\ c^{(0)}_5 \end{pmatrix} =  W^{(0)}x+b^{(0)} =
\begin{pmatrix} W^{(0)}_0 x + b^{(0)}_0 \\ W^{(0)}_1 x + b^{(0)}_1 \\ W^{(0)}_2 x + b^{(0)}_2 \\
W^{(0)}_3 x + b^{(0)}_3 \\ W^{(0)}_4 x + b^{(0)}_4 \\ W^{(0)}_5 x + b^{(0)}_5  \end{pmatrix}   $， 

然後再將結果逐項對一個非線性的函數 $f$  最後得到一個向量。
 
 $d^{(0)} = \begin{pmatrix} d^{(0)}_0 \\ d^{(0)}_1 \\ d^{(0)}_2  \\ d^{(0)}_3 \\ d^{(0)}_4 \\ d^{(0)}_5 \end{pmatrix} 
 = f({W x + b}) = \begin{pmatrix} f(c^{(0)}_0) \\ f(c^{(0)}_1) \\ f(c^{(0)}_2)  \\ f(c^{(0)}_3) \\ f(c^{(0)}_4) \\ f(c^{(0)}_5) \end{pmatrix} $
 
這裡的 $f$ 常常會用 sigmoid , tanh，或者 ReLU ( https://en.wikipedia.org/wiki/Activation_function )。

### 第 1 層
這裡接到輸出，其實和 softmax regression 一樣。

只是輸入變成 $d^{(0)}, Weight 和 Bias 現在叫做 W^{(1)} 和 b^{(1)} 

因為維度改變，現在 W^{(1)} 是 3x6 的矩陣。 後面接到的輸出都一樣。

所以線性輸出

### $ c^{(1)} =  W^{(1)} d^{(0)} + b^{(1)} $

### $ d^{(1)} =  e^{c^{(1)}} $



當輸入為 x, 最後的 softmax 預測類別是 i 的機率為
###  $q_i = Predict_{W^{(0)}, W^{(1)}, b^{(0)}, b^{(1)}}(Y=i|x)  = \frac {d^{(1)}_i} {\sum_j d^{(1)}_j}$
### 合起來看，就是 $q = \frac {d^{(1)}} {\sum_j d^{(1)}_j}$

### 問題
如果 $W^{(0)}, W^{(1)}, b^{(0)}, b^{(1)}$ 設定為 $A, b, C, d$ (C, d 與前面無關)

softmax function 用
### $\sigma (\mathbf {z} )_{j}={\frac {e^{z_{j}}}{\sum _k e^{z_{k}}}}$
表示，我們簡化上面的過程成為一個算式。

In [7]:
! cat solutions/ff_oneline.py

from IPython.display import display, Latex
display(Latex("$\sigma (Cf(Ax+b)+d)$"))

In [8]:
# 參考答案
%run solutions/ff_oneline.py

<IPython.core.display.Latex object>

### 任務：計算最後的猜測機率 $q$
設定：輸入 4 維， 輸出 3 維， 隱藏層 6 維
* 設定一些權重 $A,b,C,d$ (隨意自行填入，或者用 np.random.randint(-2,3, size=...))
* 設定輸入 $x$ (隨意自行填入，或者用 np.random.randint(-2,3, size=...))
* 自行定義 relu, sigmoid 函數 (Hint: np.maximum)
* 算出隱藏層 $z$
* 自行定義 softmax
* 算出最後的 q

In [14]:
# 請在這裡計算
np.random.seed(123433)



In [15]:
! cat solutions/ff_init_variables.py

np.random.seed(1234)
A = np.random.randint(-2,3,size=(6,4))
b = np.random.randint(-2,3,size=(6))
C = np.random.randint(-2,3,size=(3,6))
d = np.random.randint(-2,3,size=(3))
x = np.random.randint(-2,3,size=(4))

In [18]:
# print("A = ",A)
# print("b = ",b)
# print("C = ",C)
# print("d = ",d)
# print("x = ",x)

In [19]:
# 參考答案，設定權重
%run -i solutions/ff_init_variables.py
display(A)
display(b)
display(C)
display(d)
display(x)

array([[ 1,  2,  2, -2],
       [-1, -1, -1,  0],
       [ 1,  2,  2,  0],
       [ 0, -2, -2,  2],
       [-2, -1,  0, -2],
       [ 1,  2,  0,  0]])

array([ 1,  1, -2, -1,  1, -2])

array([[ 1,  0,  1,  2, -1,  1],
       [ 1,  1,  0, -1,  1,  2],
       [ 0,  1,  2, -1,  2, -2]])

array([ 2, -1, -1])

array([ 2, -1,  2, -2])

In [21]:
! cat solutions/ff_compute_z.py

def relu(x):
    return np.maximum(x, 0)
def sigmoid(x):
    return 1/(1+np.exp(-x))
z_relu = relu(A@x + b)
z_sigmoid = sigmoid(A@x + b )

In [24]:
# 參考答案 定義 relu, sigmoid 及計算 z
%run -i solutions/ff_compute_z.py
display(z_relu)
display(z_sigmoid)

array([[2., 2., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0.],
       [4., 4., 1., 2., 4., 1.],
       [1., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [2., 2., 0., 0., 2., 0.]])

array([[0.88079708, 0.88079708, 0.26894142, 0.5       , 0.88079708,
        0.26894142],
       [0.26894142, 0.26894142, 0.01798621, 0.04742587, 0.26894142,
        0.01798621],
       [0.98201379, 0.98201379, 0.73105858, 0.88079708, 0.98201379,
        0.73105858],
       [0.73105858, 0.73105858, 0.11920292, 0.26894142, 0.73105858,
        0.11920292],
       [0.04742587, 0.04742587, 0.00247262, 0.00669285, 0.04742587,
        0.00247262],
       [0.88079708, 0.88079708, 0.26894142, 0.5       , 0.88079708,
        0.26894142]])

In [22]:
! cat solutions/ff_compute_q.py

def softmax(x):
    t = np.exp(x)
    return t/t.sum()
q_relu = softmax(C @ relu(A @ x + b) + d)
q_sigmoid = softmax(C @ sigmoid(A @ x + b) + d)

In [ ]:
# 參考答案 定義 softmax 及計算 q
%run -i solutions/ff_compute_q.py
display(q_relu)
display(q_sigmoid)


### 練習
設計一個網路:
* 輸入是二進位 0 ~ 15
* 輸出依照對於 3 的餘數分成三類


In [23]:
# Hint 下面產生數字 i 的 2 進位向量
i = 13
x = Vector(i%2, (i>>1)%2, (i>>2)%2, (i>>3)%2)
x

array([[1.],
       [0.],
       [1.],
       [1.]])

In [26]:
# 請在這裡計算
x = np.array([[1,3,4,6]])
print(x.shape)


(1, 4)


In [ ]:
# 參考解答
%run -i solutions/ff_mod3.py

### 練習
設計一個網路來判斷井字棋是否有連成直線(只需要判斷其中一方即可):
* 輸入是 9 維向量，0 代表空格，1 代表有下子 
* 輸出是二維(softmax)或一維(sigmoid)皆可，用來代表 True, False

有連線的例子

```
_X_
X__
XXX

XXX
XX_
_XX

__X
_XX
X__
```

沒連線的例子
```
XX_
X__
_XX

_X_
XX_
X_X

__X
_XX
_X_
```

In [ ]:
# 請在這裡計算



In [ ]:
#參考答案
%run -i solutions/ff_tic_tac_toe.py

In [ ]:
# 測試你的答案
def my_result(x):
    # return 0 means no, 1 means yes
    return (C@relu(A@x+b)+d).argmax()
    # or sigmoid based
    # return (C@relu(A@x+b)+d) > 0

def truth(x):
    x = x.reshape(3,3)
    return (x.all(axis=0).any() or
            x.all(axis=1).any() or
            x.diagonal().all() or
            x[::-1].diagonal().all())

for i in range(512):
    x = np.array([[(i>>j)&1] for j in range(9)])
    assert my_result(x) == truth(x)
print("test passed")