In [5]:
import numpy as np

In [6]:
np.random.seed(1234)
A = np.random.randint(-2,3,size=(6,4))
b = np.random.randint(-2,3,size=(6))
C = np.random.randint(-2,3,size=(3,6))
d = np.random.randint(-2,3,size=(3))
x = np.random.randint(-2,3,size=(4))

In [7]:
def relu(x):
    return np.maximum(x, 0)
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [8]:
i = 13
x = np.array([i%2, (i>>1)%2, (i>>2)%2, (i>>3)%2])
#print(x)
#print(i%4)

In [9]:
def creatData(mod):
    data = []
    ans = []
    for i in range(50000):
        n = np.random.randint(0,16)
        yu = n%mod
        x = np.array([[n%2], [(n>>1)%2], [(n>>2)%2], [(n>>3)%2]])
        data.append(x)
        ans.append(yu)
    return np.array(data), np.array(ans)
    
#test_X,test_Y = creatData(3)

# Mod4

In [10]:
test_X,test_Y = creatData(4)
#test_X = test_X.swapaxes(1,2)
w = np.array([[-1,-1,0,0],
              [1,-1,0,0],
              [-1,1,0,0],
              [1,0,0,0]])
b = np.array([1,0,0,0])
#for i in range(len(test_Y)):
ans = np.array([(w @ t).argmax() for t in test_X])

In [11]:
print("Mod 4 : ",(ans==test_Y).mean())

Mod 4 :  1.0


# Mod3

In [12]:
test_X,test_Y = creatData(3)
w = np.array([[-1.4, -0.1,  2.8, -7.4],
              [ 7.4, -3.2, -3. , -1.9],
              [-0.5,  6. , -4.4,  5. ]])
b = np.array([[ 5.3],
              [-1.4],
              [-4. ]])

ans = np.array([(w @ t+b).argmax() for t in test_X])

In [13]:
print((ans==test_Y).mean())

0.56552


# 3x3 board

In [14]:
def Random_Matrix(row,column,start,finish):   
    matrix = np.random.randint(start,finish, size=(column,row))
    return np.array(matrix)
Matrix = []
Matrix.append([[1, 1, 1],[0, 0, 0],[0, 0, 0]])
Matrix.append([[0, 0, 0],[1, 1, 1],[0, 0, 0]])
Matrix.append([[0, 0, 0],[0, 0, 0],[1, 1, 1]])
Matrix.append([[1, 0, 0],[1, 0, 0],[1, 0, 0]])
Matrix.append([[0, 1, 0],[0, 1, 0],[0, 1, 0]])
Matrix.append([[0, 0, 1],[0, 0, 1],[0, 0, 1]])
Matrix.append([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
Matrix.append([[0, 0, 1],[0, 1, 0],[1, 0, 0]])
Matrix.append([[0, 0, 0],[0, 0, 0],[0, 0, 0]])
Matrix_array = np.array(Matrix)

Matrix_array[8]
test_Matrix= Random_Matrix(3,3,0,2)


def find_Matrix_situation(test_Matrix,Matrix_array):
    Matrix_situation=np.array([1,0])
    sumofmatrix=0
    for i in range(8):
        Matrix_multiplication=test_Matrix*Matrix_array[i]
        sumofmatrix = Matrix_multiplication.sum()
        if(sumofmatrix==3):
            Matrix_situation=np.array([0,1])
            return Matrix_situation,i,sumofmatrix
    return Matrix_situation,8,sumofmatrix   


def test(times):
    for j in range(times):
        test_Matrix= Random_Matrix(3,3,0,2)
        Matrix_situation,i,sumofmatrix=find_Matrix_situation(test_Matrix,Matrix_array)
        print("test_Matrix:")
        print(test_Matrix)
        print("match_pattern:")
        print(np.array(Matrix_array[i]))
        print("Matrix_multiplication")
    if (i<8):
        print(test_Matrix*Matrix_array[i])
    else:
        print("[0]")
    print("sumofmatrix",sumofmatrix)
    print("Matrix_situation:",Matrix_situation)


In [15]:
def creatData2(times):
    data = []
    ans = []
    for j in range(times):
        test_Matrix= Random_Matrix(3,3,0,2)
        Matrix_situation,i,sumofmatrix=find_Matrix_situation(test_Matrix,Matrix_array)
        data.append(test_Matrix)
        ans.append(Matrix_situation)
    return np.array(data), np.array(ans)
    

train_X,train_Y = creatData2(10000)

In [16]:
print(train_X[:3])
print(train_Y[:3])

[[[1 0 0]
  [1 0 0]
  [1 0 0]]

 [[0 1 0]
  [0 1 1]
  [1 1 0]]

 [[1 1 1]
  [0 1 1]
  [0 1 0]]]
[[0 1]
 [0 1]
 [0 1]]


In [19]:

W1 = np.array([[-2.7, -9.9 ,-2.9],
                [-6.9, -1.7, -3.2],
                [ 2.4, -7.8,  8.1],
                [ 4.8, -2.1, -2.5],
                [ 0.9, -4.1, -3.5],
                [-7.9,  9.6,  4.8],
                [-5.9,  3. ,  0.2],
                [-2.7,  2.2,  6.6],
                [ 9.9, -1.6, -1.9],
                [ 4.4, -8.1, -1.6]])
W2 = np.array([[-9.4,  4.7, -9.3, -8.,  -7.5, -4.4,  6.1,  5.5, -7.9,  1.7],
               [ 1.9,  6.3,  3.6, -2.2, -0.8,  1.1,  1.2, -1.,   4.8,  6.2]])
W3 = np.array([[8.1],
               [1.5],
               [1.7]])
b = np.array([[ -1.5,   9.5,   3.4],
              [ -7.4,   4.2,   6.3],
              [  5.2,   9. ,   2.8],
              [  3.6,  -6.8,  -0.4],
              [ -7.3,  -7.3,   7.8],
              [  1. ,   5. ,  -2.2],
              [-10. ,  -7.8,   2.4],
              [  2.6,   7.7,  -2.1],
              [ -5.3,   1.3,   6. ],
              [ -0.7,   3.2,   5.3]])
ans = np.array([sigmoid((relu(W2@(relu(W1 @ t+b))))@W3).argmax() for t in train_X])
#print(ans)
#print(train_Y)
#peic = (ans==train_Y.argmax()).mean()


In [20]:
print((ans==train_Y.argmax()).mean())

1.0
