In [9]:
from PIL import Image
import numpy as np

In [10]:
np.random.seed(1234)
A = np.random.randint(-2,3,size=(6,4))
b = np.random.randint(-2,3,size=(6))
C = np.random.randint(-2,3,size=(3,6))
d = np.random.randint(-2,3,size=(3))
x = np.random.randint(-2,3,size=(4))

In [11]:
import os
import urllib
from urllib.request import urlretrieve
dataset = 'mnist.pkl.gz'
def reporthook(a,b,c):
    print("\rdownloading: %5.1f%%"%(a*b*100.0/c), end="")
    
if not os.path.isfile(dataset):
        origin = "https://github.com/mnielsen/neural-networks-and-deep-learning/raw/master/data/mnist.pkl.gz"
        print('Downloading data from %s' % origin)
        urlretrieve(origin, dataset, reporthook=reporthook)

In [12]:
import gzip
import pickle
with gzip.open(dataset, 'rb') as f:
    train_set, validation_set, test_set = pickle.load(f, encoding='latin1')

In [13]:
print("Class : %d" % len(train_set))
print("len Class 1 : %d" % len(train_set[0]))
print("len Class 2 : %d" % len(train_set[1]))

print("image len Class 1 : %d" % len(train_set[0][0]))

Class : 2
len Class 1 : 50000
len Class 2 : 50000
image len Class 1 : 784


In [14]:
train_X, train_y = train_set
test_X, test_y = test_set

In [15]:
# print(train_X[:5])
# print(train_y[:5])
# print(test_X[:5])
# print(test_y[:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[5 0 4 1 9]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[7 2 1 0 4]


In [17]:
from IPython.display import display
def showX(X):
    int_X = (X*255).clip(0,255).astype('uint8')
    # N*784 -> N*28*28 -> 28*N*28 -> 28 * 28N
    int_X_reshape = int_X.reshape(-1,28,28).swapaxes(0,1).reshape(28,-1)
    display(Image.fromarray(int_X_reshape))
    
#showX(train_X[:10])
#print(train_y[:10])

[5 0 4 1 9 2 1 3 1 4]


In [18]:
train_X /= np.linalg.norm(train_X, axis=1, keepdims=True)
test_X /= np.linalg.norm(test_X, axis=1, keepdims=True)

In [19]:
A = test_X @ train_X.T

In [20]:
predict_y = train_y[A.argmax(axis=1)]

In [21]:
print((predict_y == test_y).mean())

0.9708
